Remove (unused) argument names
jonas-schievink/xml-rpc-rs pull request #7
Opened 2016-10-15 22:02 UTC by bwbuchanan

XML-RPC doesn't support named arguments, so it's confusing/misleading to have them in the Rust API.

2016-10-15 23:18 UTC, jonas-schievink requested changes
Agreed.

Initially, I planned to provide a type-safe interface to an XML-RPC endpoint, but the design turned out to be more complex than I liked, so I think it's a good idea to make this crate as close to raw XML-RPC as possible and maybe revisit that idea later.

2016-10-15 23:18 UTC, jonas-schievink commented on src/request.rs
> +        for ref value in &self.args {
The ref shouldn't be necessary here

2016-10-15 23:33 UTC, bwbuchanan commented on src/request.rs
> +        for ref value in &self.args {
Yes, just pushed again without it.

2016-10-16 00:06 UTC, jonas-schievink approved these changes

2016-10-16 00:06 UTC, merged